create table users (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  email varchar(255) not null
);

insert into users (name, email) values ('Alice', 'alice@example.com');
insert into users (name, email) values ('Bob', 'bob@example.com');
insert into users (name, email) values ('Charlie', 'charlie@example.com');
insert into users (name, email) values ('David', 'david@test.com');
insert into users (name, email) values ('Eva', 'eva@example.com'); 